{
  "language": "php",
  "matrix": {
    "include": [
      {
        "php": 5.5,
        "env": "WP_TRAVISCI=travis:js"
      },
      {
        "php": 5.2,
        "env": "WP_TRAVISCI=travis:phpunit"
      },
      {
        "php": 5.3,
        "env": "WP_TRAVISCI=travis:phpunit"
      },
      {
        "php": 5.4,
        "env": "WP_TRAVISCI=travis:phpunit"
      },
      {
        "php": 5.5,
        "env": "WP_TRAVISCI=travis:phpunit"
      },
      {
        "php": 5.6,
        "env": "WP_TRAVISCI=travis:phpunit"
      },
      {
        "php": "hhvm",
        "env": "WP_TRAVISCI=travis:phpunit"
      }
    ],
    "allow_failures": [
      {
        "php": 5.6
      },
      {
        "php": "hhvm"
      }
    ],
    "fast_finish": true
  },
  "env": "WP_VERSION=master WP_MULTISITE=1",
  "before_install": [
    "WP_CORE_DIR=/tmp/wordpress/",
    "if [[ \"$WP_TRAVISCI\" == \"travis:phpunit\" ]]; then pwd\n    mysql -e \"CREATE DATABASE wordpress_tests;\" -uroot\n    cp tests/wp-tests-config-sample.php tests/wp-tests-config.php\n    sed -i \"s/pdb/wordpress_tests/\" tests/wp-tests-config.php\n    sed -i \"s/pdbuser/travis/\" tests/wp-tests-config.php\n    sed -i \"s/04-3J31cd08k5B//\" tests/wp-tests-config.php\n    \nfi\n"
  ],
  "script": "phpunit -c tests/phpunit.xml.dist"
}
